version: "3"
services:
  postgres-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medicaments
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ../src/main/resources/db/changelog:/liquibase/changelog
    command: --driver=org.postgresql.Driver --url="jdbc:postgresql://postgres-db:5432/medicaments" --defaultSchemaName=public --changeLogFile=db.changelog-master.yaml --username=postgres --password=postgres  --logLevel=info update
    depends_on:
      - postgres-db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./web/build/:/usr/share/nginx/html
      - ./web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    image: openjdk:17
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./medicamentos.jar:/medicamentos.jar"
      - "./medicamentos.xlsx:/medicamentos.xlsx"
    command: [ 'java', '-jar', '/medicamentos.jar' ]
