server:
  port: 8080

spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/medicaments
    password: postgres
    username: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aws:
  credentials:
    access-key: AKIA4YKBJIG2CQL56CID
    secret-key: 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
    bucket-name: medicaments-tcc-ufg

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

