INSERT INTO pharmaceuticalform (code, description) VALUES ('DEFAULT', 'DEFAULT');

INSERT INTO states (id, name, code) VALUES ('52','Goiás', 'GO');
INSERT INTO states (id, name, code) VALUES ('51','Mato Grosso', 'MT');
INSERT INTO states (id, name, code) VALUES ('50','Mato Grosso do Sul', 'MS');
INSERT INTO states (id, name, code) VALUES ('43','Rio Grande do Sul', 'RS');
INSERT INTO states (id, name, code) VALUES ('42','Santa Catarina', 'SC');
INSERT INTO states (id, name, code) VALUES ('41','Paraná', 'PR');
INSERT INTO states (id, name, code) VALUES ('35','São Paulo', 'SP');
INSERT INTO states (id, name, code) VALUES ('33','Rio de Janeiro', 'RJ');
INSERT INTO states (id, name, code) VALUES ('32','Espírito Santo', 'ES');
INSERT INTO states (id, name, code) VALUES ('31','Minas Gerais', 'MG');
INSERT INTO states (id, name, code) VALUES ('29','Bahia','BA');
INSERT INTO states (id, name, code) VALUES ('28','Sergipe','SE');
INSERT INTO states (id, name, code) VALUES ('27','Alagoas','AL');
INSERT INTO states (id, name, code) VALUES ('26','Pernambuco','PE');
INSERT INTO states (id, name, code) VALUES ('25','Paraíba','PB');
INSERT INTO states (id, name, code) VALUES ('24','Rio Grande do Norte','RN');
INSERT INTO states (id, name, code) VALUES ('23','Ceará','CE');
INSERT INTO states (id, name, code) VALUES ('22','Piau','PI');
INSERT INTO states (id, name, code) VALUES ('21','Maranhão','MA');
INSERT INTO states (id, name, code) VALUES ('17','Tocantins','TO');
INSERT INTO states (id, name, code) VALUES ('16','Amapá','AP');
INSERT INTO states (id, name, code) VALUES ('15','Pará','PA');
INSERT INTO states (id, name, code) VALUES ('14','Roraima','RR');
INSERT INTO states (id, name, code) VALUES ('13','Amazonas','AM');
INSERT INTO states (id, name, code) VALUES ('12','Acre','AC');
INSERT INTO states (id, name, code) VALUES ('11','Rondônia','RO');
